version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node
    depends_on:
      - mysql
    ports:
      - ${APP_PORT-3000}:${APP_PORT-3000}
    volumes:
      - ./node-app:/node-app
      - ./.env:/node-app/.env
    networks:
      - my-network

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - ${MYSQLDB_LOCAL_PORT:-3306}:${MYSQLDB_DOCKER_PORT:-3306}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - ${FORWARD_PHPMYADMIN_PORT:-8081}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    networks:
        - my-network

volumes:
  mysql:

networks:
  my-network:
      driver: bridge